### PR TITLE
Api and Implementation

### PR DESCRIPTION
**Pull request by artemik**

### CODE REVIEW

**Comment by mcupak** [comment]
@artemik The code itself looks really good, very clean and nicely documented. However, the client doesn't really work for me. I noticed the following problems:
- The main functionality, which is beacon queries, is missing. How do I query a beacon? (see the parameters for the responses endpoint: https://beacon-network.org/#/developers/api/beacon-network#bn-responses).
- Requests to endpoints returning enums (e.g. references, chromosomes, alleles) don't work due to a serialization exception. The server uses MOXy and JAX-RS, if that helps.

I also have a few minor suggestions:
- I'm not sure I understand InternalException and UnexpectedErrorStatusException - are they needed? It just seems to me that you would either throw BeaconNetworkClientException for client errors, or ErrorStatusException (or its child) for server errors. Did you change your mind about exceptions having a common prefix?
- Can you add public class-level modifier to classes?
- beacon-network-dto uses (Lombok)[https://projectlombok.org/] to get rid of getters, setters, constructors  and other boilerplate. Since it's already a dependency, do you want to use it?
- It's a good practice to have versions of dependencies in the parent pom (dependencyManagement section). The modules would then omit the version tags completely and the versions will be resolved from the parent pom.
- Add a license header to java files, before the package declaration. You should configure your IDE to do this automatically. We're currently using Apache 2.0.

As discussed earlier today, tests are needed as well.

Keeping open until these issues are addressed.

**Comment by artemik** [comment]
- fixed some client methods input parameters, now beacon querying is working;
- used lombok for ErrorDto;
- moved dependencies from child POMs to the parent one;
- added license headers dependencies from child POMs to the parent one.

Work on adding tests.

**Comment by artemik** [comment]
@mcupak 
- fixed bugs;
- finished writing tests, written on Groovy using WireMock.

**Comment by mcupak** [comment]
This is great @artemik, excellent job with the tests in particular. I have a few minor suggestions:
- getResponses() should probably allow an empty beaconIds list. If you look at the [API docs](https://beacon-network.org/#/developers/api/beacon-network#bn-responses), you'll see that parameter is optional - if not specified, all the beacons are queried. This is very convenient and allows the user to query everything without hitting the beacon endpoint first.
- Switch the order of parameters in getResponse() and getResponses() - I'd suggest chromosome, position, allele, reference, beacon. Having allele come after position would feel more natural for the user, since that order matches a well-known format for genomic coordinates.
- Move Javadoc from public methods in BeaconNetworkClientImpl to BeaconNetworkClient. This helps IDEs with Javadoc display (they usually load it automatically from the interface when using the implementation, and it also appears when you refer to the interface directly, which is what you typically do).
- I'm wondering if InternalException should be runtime. It felt weird to catch it, since it's for such unexpected problems. WDYT?

**Comment by artemik** [comment]
@mcupak 
Fixed all the issues mentioned. I also increased the read time out of the underlying HTTP client to 5 minutes as it occurs querying the beacons may take quite a long take.

**Pull request merged**
